services:
  server:
    image: ${DOCKER_REGISTRY-}server
    ports:
      - "8080:8080"
      - "8081:8081"
    build:
      context: ..
      dockerfile: ./Server/Dockerfile
    environment:
      - ConnectionString=Host=database;Port=5432;Username=postgres;Password=password;Database=identity
    depends_on:
      migrator:
        condition: service_completed_successfully

  migrator:
    build:
      context: ..
      dockerfile: ./Migrator/Dockerfile
    environment:
      - ConnectionString=Host=database;Port=5432;Username=postgres;Password=password;Database=identity
    networks:
      - default
    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=identity
    healthcheck:
       test: ["CMD", "pg_isready", "-q", "-d", "identity", "-U", "postgres"]
       interval: 1s
       timeout: 60s
       retries: 60
       start_period: 80s
